### ISSUE TITLE
Error when running `sloth issues --csv`

### ISSUE THREAD

**Issue by danoscarmike** [JustinBeckwith/sloth#1]
```
module.js:549
    throw err;
    ^

Error: Cannot find module '../../labels.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/@justinbeckwith/sloth/build/src/util.js:8:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by danoscarmike** [comment]
`labels.json` has not been installed when I updated the package.

`danom@penguin:/usr/lib/node_modules/@justinbeckwith/sloth$ ls`
`build  node_modules  package.json  README.md  repos.json`

**Comment by JustinBeckwith** [comment]
Fixed in https://github.com/JustinBeckwith/sloth/commit/9620d7aea1d6ba53c5fe37570a2c868e43c64a1d

I just cut a new release, so `npm install -g @justinbeckwith/sloth` should work.
